<?php
$innerPage=false;
include("templates/header.php");
include("sections/_splash.php");
include("sections/_home_request-form.php");
include("sections/_home_services.php");
include("sections/_home_steps.php");
include("sections/_home_why-st7.php");
include("sections/_footer.php");
include("templates/footer.php");